
services:
  db:
    image: mysql
    networks: 
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress 
      - MYSQL_DATABASE=wordpress 
      - MYSQL_USER=wordpress 
      - MYSQL_PASSWORD=wordpress
    volumes:
      - mysql:/var/lib/mysql
  frontend:
    image: wordpress
    networks:
      - frontend
      - backend
    environment:
      - WORDPRESS_DB_HOST=db:3306 
      - WORDPRESS_DB_USER=wordpress 
      - WORDPRESS_DB_PASSWORD=wordpress 
      - WORDPRESS_DB_NAME=wordpress 
    ports:
      - "8000:80"
    volumes:
      - wordpress:/var/www/html
networks:
  backend:
  frontend:

volumes:
  mysql:
  wordpress:
